version: '3'

services:
  mysql-test1:
    image: mysql:8.0
    ports:
      - "3307:3306"
    container_name: mysql-test1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=test
    volumes:
      - ./data/test1/:/var/lib/mysql            

  mysql-test2:
    image: mysql:8.0
    ports:
      - "3308:3306"
    container_name: mysql-test2
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=test
    volumes:
      - ./data/test2/:/var/lib/mysql
