version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    container_name: concert-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ../data/mysql/:/var/lib/mysql

  redis-lock:
    image: redis:7.0
    container_name: redis-lock
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/:/data
  redis:
    image: redis:7.0
    container_name: redis-queue
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis/:/data


networks:
  default:
    driver: bridge
